@startuml
!theme materia-outline
skinparam classAttributeIconSize 0
hide empty members
hide circle
'left to right direction

entity Patient {
  <b>identifiers</b>: Identifier[]
  <b>names</b>: Name[]
  <b>dateOfBirth</b>: Date
  <b>gender</b>: Code
  addresses: Address[]
  contacts: Contact[]
}

entity Identifier {
  <b>value</b>: String
  <b>issuer</b>: String
  type: Code
}

entity Name {
  <b>text</b>: String
  family: String
  given: String
  fatherName: String
}

entity Contact {
  <b>value</b>: String
  type: Code
  use: Code
}

entity Address {
  <b>text</b>: String
  use: Code
  streetName: String
  houseNumber: String
  city: String
  postalCode: String
  country: Code
}

enum Gender {
  FEMALE
  MALE
  UNKNOWN
}

enum IdentifierType {
  PASSPORT NUMBER
  MEDICAL RECORD NUMBER
  TAX ID
  NATIONAL INSURANCE ID
  SOCIAL BENEFICIARY ID
  ...
}

enum ContactUse {
  HOME
  WORK
  OLD
}

enum ContactType {
  PHONE
  EMAIL
}

enum AddressUse {
  HOME
  WORK
  OLD
}

enum Country {
  GREECE
  CYPRUS
  NORTH MACEDONIA
  ALBANIA
  ...
}

Patient::identifiers "1" -- "1..*" Identifier
Patient::names "1" -- "1..*" Name
Patient::gender "1" -- "1" Gender
Patient::addresses "1" -- "0..*" Address
Patient::contacts "1" -- "0..*" Contact
Identifier::type "1" -- "0..1" IdentifierType
Contact::use "1" -- "0..1" ContactUse
Contact::type "1" -- "0..1" ContactType
Address::use "1" -- "0..1" AddressUse
Address::country "1" -- "0..1" Country
@enduml
