@startuml
!theme materia-outline
skinparam classAttributeIconSize 0
hide empty members
hide circle

entity Professional {
  <b>identifiers</b>: Identifier[]
  <b>name</b>: Name
  gender: Code
  addresses: Address[]
  contacts: Contact[]
  <b>specialties</b>: Code[]
}

entity Identifier {
  <b>value</b>: String
  <b>issuer</b>: String
  type: Code
}

entity Name {
  text: String
  family: String
  given: String
  fatherName: String
}

entity Contact {
  <b>value</b>: String
  type: Code
  use: <b><i><color:#1B7DCB>#WORK</color></i></b>
}

enum Specialty {
  GENERAL/FAMILY MEDICINE
  CARDIOLOGY
  PEDIATRICS
  RADIOLOGY
  ...
}

entity Address {
  text: String
  use: <b><i><color:#1B7DCB>#WORK</color></i></b>
  streetName: String
  houseNumber: String
  city: String
  postalCode: String
  country: <b><i><color:#1B7DCB>#GREECE</color></i></b>
}

enum Gender {
  FEMALE
  MALE
  <del>UNKNOWN</del>
}

enum IdentifierType {
  EMPLOYER NUMBER
  PROVIDER NUMBER
  MEDICAL LICENSE NUMBER
  ...
}

enum ContactType {
	PHONE
	EMAIL
}

Professional::identifiers "1" -- "1..*" Identifier
Professional::name "1" -- "1" Name
Professional::gender "1" -- "1" Gender
Professional::addresses "1" -- "0..*" Address
Professional::contacts "1" -- "0..*" Contact
Professional::specialties "1" -- "1..*" Specialty
Identifier::type "1" -- "0..1" IdentifierType
Contact::type "1" -- "0..1" ContactType
@enduml
