@startuml
!theme materia-outline
skinparam classAttributeIconSize 0
hide empty members
hide circle
'left to right direction

entity Professional {
  identifiers: Identifier[]
  name: Name
  gender: Code
  addresses: Address[]
  contacts: Contact[]
  specialties: Code[]
}

entity Identifier {
  type: Code
  issuer: String
  value: String
}

entity Name {
  text: String
  family: String
  given: String
  fatherName: String
}

entity Contact {
  use: <b><color:#1B7DCB>WORK</color></b>
  type: Code
  value: String
}

enum Specialty {
  GENERAL/FAMILY MEDICINE
  CARDIOLOGY
  PEDIATRICS
  RADIOLOGY
  ...
}

entity Address {
  text: String
  use: <b><color:#1B7DCB>WORK</color></b>
  streetName: String
  houseNumber: String
  city: String
  postalCode: String
  country: <b><color:#1B7DCB>GREECE</color></b>
}

enum Gender {
  FEMALE
  MALE
}

enum IdentifierType {
  EMPLOYER NUMBER
  PROVIDER NUMBER
  MEDICAL LICENSE NUMBER
  ...
}

enum ContactType {
	PHONE
	EMAIL
}

Professional::identifiers "1" -- "1..*" Identifier
Professional::name "1" -- "1" Name
Professional::gender "1" -- "1" Gender
Professional::addresses "1" -- "1..*" Address
Professional::contacts "1" -- "1..*" Contact
Professional::specialties "1" -- "1..*" Specialty
Identifier::type "1" -- "1" IdentifierType
Contact::type "1" -- "1" ContactType
@enduml
