@startuml
!theme materia-outline
skinparam classAttributeIconSize 0
hide empty members
hide circle

entity Provider {
  <b>identifier</b>: Identifier
  <b>name</b>: String
  type: Code
  address: Address
  contacts: Contact[]
  parent: Provider
}

entity Identifier {
  <b>value</b>: String
  <b>issuer</b>: String
  type: <b><i><color:#1B7DCB>#PROVIDER NUMBER</color></i></b>
}

entity Contact {
  <b>value</b>: String
  type: Code
  use: <b><i><color:#1B7DCB>#WORK</color></i></b>
}

enum ProviderType {
  PRIMARY HEALTH CARE UNIT
  MUNICIPAL CLINIC
  REGIONAL CLINIC
  DAY CARE UNIT
  HOSPITAL
  ...
}

entity Address {
  text: String
  use: <b><i><color:#1B7DCB>#WORK</color></i></b>
  streetName: String
  houseNumber: String
  city: String
  postalCode: String
  country: <b><i><color:#1B7DCB>#GREECE</color></i></b>
}

enum ContactType {
	PHONE
	EMAIL
}

Provider::identifier "1" -- "1" Identifier
Provider::type "1" -- "0..1" ProviderType
Provider::address "1" -- "0..1" Address
Provider::contacts "1" -- "0..*" Contact
Provider::parent "1" -- "0..1" Provider
Contact::type "1" -- "0..1" ContactType
@enduml
