@startuml
!theme materia-outline
skinparam classAttributeIconSize 0
hide empty members
hide circle

entity Service {
  <b>identifier</b>: Identifier
  <b>name</b>: String
  <b>type</b>: Code
  category: Code
  address: Address
  contacts: Contact[]
  <b>provider</b>: Provider
}

entity Identifier {
  <b>value</b>: String
  <b>issuer</b>: String
  type: <b><i><color:#1B7DCB>#FILLER ID</color></i></b>
}

entity Contact {
  <b>value</b>: String
  type: Code
  use: <b><i><color:#1B7DCB>#WORK</color></i></b>
}

enum ServiceCategory {
  DIAGNOSTIC PROCEDURES
  IMAGING DIAGNOSTIC METHODS
  SURGICAL PROCEDURES
  NON-SURGICAL THERAPEUTIC PROCEDURES
  OTHER PROCEDURES
  ...
}

enum ServiceType {
  MAGNETIC ANGIOGRAPHY
  RADIOISOTOPIC CYSTOGRAM
  BIOPSIES NEPHROSTOMIES
  CT SCAN
  ...
}

entity Address {
  text: String
  use: <b><i><color:#1B7DCB>#WORK</color></i></b>
  streetName: String
  houseNumber: String
  city: String
  postalCode: String
  country: <b><i><color:#1B7DCB>#GREECE</color></i></b>
}

enum ContactType {
	PHONE
	EMAIL
}

Service::identifier "1" -- "1" Identifier
Service::category "1" -- "0..1" ServiceCategory
Service::type "1" -- "1" ServiceType
Service::address "1" -- "0..1" Address
Service::contacts "1" -- "0..*" Contact
Contact::type "1" -- "0..1" ContactType
@enduml
